게임상점 01
utilForever/ProgrammingPractice pull request #15
Opened 2017-05-28 09:44 UTC by LeeInkyu

자바 어렵지만 재밌게 배우고 있습니다!
코드 가독성이 어떻게 하면 좋아질지 생각하고 있긴 한데, 이런 고민을 한 적이 처음이라...
앞으로 가독성에 더 신경쓰겠습니당

2017-05-28 12:31 UTC, utilForever commented on Solutions/LeeInkyu/Game Shop/02/Armor.java
> +        System.out.println();
Superclass와 Subclass 관계이므로, 함수가 오버라이드됩니다.
이 때, super 키워드를 활용하면 중복되는 코드를 생략할 수 있습니다.

2017-05-28 12:33 UTC, utilForever commented on Solutions/LeeInkyu/Game Shop/01/Item.java
> +    public void Describe()
저번 과제에서도 피드백 드렸지만, Java에서는 멤버 함수를 소문자로 시작하는걸 권장하고 있습니다.
하지만 강제하는 것은 아니므로 앞으로의 과제 제출에서는 이에 대한 피드백을 하지 않겠습니다.
(코딩 규칙은 본인의 선택이니까요)

2017-05-28 12:33 UTC, utilForever commented on Solutions/LeeInkyu/Game Shop/02/Weapon.java
> +        System.out.println();
Superclass와 Subclass 관계이므로, 함수가 오버라이드됩니다.
이 때, super 키워드를 활용하면 중복되는 코드를 생략할 수 있습니다.

2017-05-28 12:34 UTC, utilForever commented on Solutions/LeeInkyu/Game Shop/02/main.java
> +        Armor SteelArmor = new Armor("Steel Armor", "Protective covering made by steel", 15, 805, 18);
다형성을 활용한 예제입니다.
코드를 다음과 같이 수정해주세요.
Item Excalibur = new Weapon("Excalibur", "The legendary sword of King Arthur", 12, 1024, 24);
Item SteelArmor = new Armor("Steel Armor", "Protective covering made by steel", 15, 805, 18);

2017-05-28 12:34 UTC, utilForever requested changes
main 함수에서 고쳐야 할 코드가 있습니다.
확인하신 뒤 수정해주세요. 일단 보류하겠습니다.

2017-05-29 10:31 UTC, utilForever commented on Solutions/LeeInkyu/Game Shop/02/Weapon.java
> +    public Weapon(String namePm, String descriptionPm, int weightPm, int valuePm, int damagePm)
이 때 super를 활용하면 중복되는 코드를 줄일 수 있습니다.

2017-05-29 10:31 UTC, utilForever commented on Solutions/LeeInkyu/Game Shop/02/Armor.java
> +    public Armor(String namePm, String descriptionPm, int weightPm, int valuePm, int defensePm)
이 때 super를 활용하면 중복되는 코드를 줄일 수 있습니다.

2017-05-29 10:32 UTC, utilForever approved these changes
고생하셨습니다.
다음 과제에서는 super 키워드를 활용해보기 바랍니다.

2017-05-29 10:32 UTC, merged

2017-05-29 12:16 UTC, LeeInkyu commented
넵 감사합니다! super 더 공부할게요...