Game Shop part1 and part2
utilForever/ProgrammingPractice pull request #18
Opened 2017-05-29 05:44 UTC by Han3l

Game Shop part1 and part2 from han3l

2017-05-29 05:45 UTC, utilForever commented
안녕하세요, 실례지만 제가 알고 계신 분일까요?
성함을 알려주시면 감사하겠습니다. :^)

2017-05-29 05:48 UTC, Han3l commented
윤서 !

2017-05-29 05:48 UTC, utilForever commented
그...그렇군...

2017-05-29 05:49 UTC, Han3l commented
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2017-05-29 12:55 UTC, utilForever commented on Solutions/han3l/Game Shop/Part1/Item.cpp
> +Item::Item(std::string name, std::string description, int weight, int value)
멤버 이니셜라이저를 사용하면 초기화와 동시에 값을 할당할 수 있습니다.
std::string name = 쓰레기값;
this->name = name;
과
std:;string name = name;
은 다릅니다.

2017-05-29 12:55 UTC, utilForever commented on Solutions/han3l/Game Shop/Part2/Item.cpp
> +void Weapon::Describe()
출력문에 중복되는 코드가 많네요.
Item::Describe()를 사용하면 중복되는 코드를 생략할 수 있습니다.

2017-05-29 12:56 UTC, utilForever commented on Solutions/han3l/Game Shop/Part2/Item.h
> +	~Item();
소멸자에 반드시 virtual을 사용해야 합니다!

2017-05-29 12:56 UTC, utilForever commented on Solutions/han3l/Game Shop/Part2/Item.h
> +	void Describe();
오버라이딩하는 함수의 경우, override 키워드를 붙여주면 오버라이딩 조건을 만족하는지 확인할 수 있습니다.
```void Describe() override;```

2017-05-29 12:57 UTC, utilForever requested changes
수고하셨습니다. 가독성에는 큰 문제가 없습니다.
하지만 소멸자에 virtual 키워드를 적지 않은 문제가 있습니다.
확인하시고 수정한 코드를 올려주시기 바랍니다.

2017-05-29 13:28 UTC, Han3l commented on Solutions/han3l/Game Shop/Part2/Item.cpp
> +void Weapon::Describe()
이것은 저의 실수입니다..

2017-05-29 15:58 UTC, utilForever requested changes
Amor는 오타인 거 같네요. Armor로 고쳐주세요.
그리고 Item과 Weapon/Armor는 상속 관계입니다.
따라서 부모 클래스의 소멸자에 virtual을 붙여야 합니다.
이 부분을 수정해주시기 바랍니다.

2017-05-29 23:13 UTC, Han3l commented
수정 완료 했습니다 !

2017-05-30 00:06 UTC, utilForever approved these changes
수정 확인했습니다. 고생하셨습니다.

2017-05-30 00:06 UTC, merged