3번째 과제 완료!
utilForever/ProgrammingPractice pull request #28
Opened 2017-06-05 02:57 UTC by IdeaBank

아직 실력이 부족합니다...

2017-06-18 14:56 UTC, utilForever commented on Solutions/IdeaBank/Game Shop/3/ShopClass.h
> +	void Describe();
가상 함수의 오버라이딩 조건을 확인하는 override 키워드를 사용하면 좋습니다.
```void Describe() override```

2017-06-18 14:57 UTC, utilForever commented on Solutions/IdeaBank/Game Shop/3/ShopClass.h
> +Weapon::Weapon(std::string name, std::string description, int weight, int value, int damage)
Item의 클래스를 멤버 이니셜라이저로 호출하면 중복되는 코드를 줄일 수 있습니다.

2017-06-18 14:57 UTC, utilForever commented on Solutions/IdeaBank/Game Shop/3/ShopClass.h
> +void Weapon::Describe()
Item 클래스의 Describe()를 호출하면 중복된는 코드를 줄일 수 있습니다.

2017-06-18 14:59 UTC, utilForever commented on Solutions/IdeaBank/Game Shop/3/Test.cpp
> +	} while (select != 3);
아래 코드를 동적 할당했는데, 프로그램 실행이 끝난 뒤 동적 할당 해제를 하지 않고 있습니다.
```
std::vector<Item*> waShopItems;
std::vector<Item*> potionShopItems;
```
delete 키워드를 통해 동적 할당 해제를 해주기 바랍니다.

2017-06-18 14:59 UTC, utilForever requested changes
로직에는 큰 문제가 없으나, 몇몇 개선 사항이 보입니다.
특히 동적 할당한 리소스를 해제하지 않는 문제가 있습니다.
이 부분을 반영해 수정해주시기 바랍니다.

2017-06-19 00:16 UTC, IdeaBank commented
수정했습니다 :)

2017-06-20 14:25 UTC, utilForever approved these changes
요청한 부분들 잘 반영해 줬네. 고생했어~

2017-06-20 14:26 UTC, merged