Item 3
utilForever/ProgrammingPractice pull request #30
Opened 2017-06-05 03:55 UTC by whiteWeed

게임상점 3 제출해요

2017-06-18 15:59 UTC, utilForever commented on Solutions/whiteWeed/Game Shop/3/ShopTest.java
> +	public static void select(){
select() 함수가 재귀 호출되는 문제가 있습니다.

2017-06-18 16:00 UTC, utilForever requested changes
함수가 재귀 형태로 호출되는 부분이 있어서 확인이 필요합니다. 보시고 답변 남겨주시거나 코드를 고쳐주세요.
p.s. GradeManagementSystem 코드가 같이 들어갔네요.

2017-07-01 09:00 UTC, whiteWeed reviewed
ㅇㅁㅇ... 내가 뭘 누른거지...

2017-07-11 11:37 UTC, utilForever reviewed
GradeManagementSystem 코드랑 Shop 코드랑 섞여 있어서 확인하기가 힘드네요. 분리해서 다시 올려주세요.

2017-07-11 11:37 UTC, closed without merging