Grade Management System part 1
utilForever/ProgrammingPractice pull request #33
Opened 2017-06-14 06:27 UTC by Han3l

2017-06-14 06:35 UTC, Han3l commented
실수로 닫아버렸습니다...

2017-06-20 14:55 UTC, utilForever commented on Solutions/han3l/Grade Management System/part1/gms.cpp
> +	for (int i = 0; i < 5; i++)
std::sort나 std::qsort를 사용해도 좋습니다.

2017-06-20 14:55 UTC, utilForever commented on Solutions/han3l/Grade Management System/part1/gms.cpp
> +	delete[] &students;
동적 할당을 해제하는 방법이 잘못되었습니다. 고치기 바랍니다.

2017-06-20 14:57 UTC, utilForever commented on Solutions/han3l/Grade Management System/part1/gms.cpp
> +		students[i] = new Student(name, scores);
Rvalue reference를 사용할 수 있지 않을까 생각해 보세요.

2017-06-20 14:58 UTC, utilForever requested changes
프로그래밍하느라 고생했어.
몇 가지 의견을 남겼는데, 참고하길 바라.
메모리 동적 할당 해제 문제가 있는데 이거는 수정해서 다시 제출해주길 바라. 그럼!

2017-06-21 02:55 UTC, Han3l commented on Solutions/han3l/Grade Management System/part1/gms.cpp
> +		students[i] = new Student(name, scores);
Rvalue는 항상 어렵...

2017-06-21 02:56 UTC, Han3l commented on Solutions/han3l/Grade Management System/part1/gms.cpp
> +	for (int i = 0; i < 5; i++)
알고리즘 헤더파일을 최대한 안써보려고 이렇게 했습니다.

2017-07-11 12:21 UTC, utilForever approved these changes
고생했습니다. 코드 리뷰를 받으면서 점점 발전하는 모습이 보입니다. :^)

2017-07-11 12:21 UTC, merged