Grade Management System 01
utilForever/ProgrammingPractice pull request #6
Opened 2017-05-27 02:24 UTC by LeeInkyu

Git 사용법을 잘 모르겠어서... 잘 한게 맞는지 모르겠어요 :)
처음 자바로 짠 프로그램이라서 제가 짠게 맞는건지 틀린 건지 잘 모르겠어요...

2017-05-27 05:12 UTC, utilForever commented on Solutions/LeeInkyu/Grade Management System/1/Student.java
> +    byte Kscore,Mscore,Escore;
멤버 변수의 이름은 의미가 명확할수록 좋습니다.
Kscore, Mscore, Escore보다는 korean_score, math_score, english_score라는 이름이 좋겠습니다.

2017-05-27 05:14 UTC, utilForever commented on Solutions/LeeInkyu/Grade Management System/1/Student.java
> +    public Student(String namePm,byte Kpm,byte Mpm,byte Epm)
여기서 Pm은 무슨 의미인가요?

2017-05-27 05:16 UTC, utilForever commented on Solutions/LeeInkyu/Grade Management System/1/Student.java
> +    public void infoPrint()
멤버 함수의 이름은 동사 + 명사로 작성하면 더욱 가독성이 올라갑니다.
infoPrint()보다는 printInfo()가 좀 더 보기 좋겠습니다.

2017-05-27 05:19 UTC, utilForever commented on Solutions/LeeInkyu/Grade Management System/1/StudentHandler.java
> +    short Ksum=0,Msum=0,Esum=0;
여기도 마찬가지로 Ksum, Msum, Esum보다는
korean_score_sum, math_score_sum, english_score_sum이 좋겠습니다.

2017-05-27 05:20 UTC, utilForever commented on Solutions/LeeInkyu/Grade Management System/1/StudentHandler.java
> +    public void StudentSort(Student[] stdPm) //각 학생별 순위 구하기
각 학생별로 순위를 구하는 함수라면, 함수 이름이 StudentSort보다는 getRank가 더 좋지 않을까요?

2017-05-27 05:26 UTC, utilForever commented on Solutions/LeeInkyu/Grade Management System/1/StudentHandler.java
> +                stdPm[i].rank = (short)(6-cnt);
2중 for문 안에서 rank를 매 번 할당할 필요없이,
cnt를 모두 계산한 후 마지막에 할당하면 되지 않을까 싶네요.

2017-05-27 05:27 UTC, utilForever commented on Solutions/LeeInkyu/Grade Management System/1/StudentHandler.java
> +    public void StudentPrint(Student[] stdPm) //학생들 정보 출력하기
학생들의 정보를 출력하는 함수라면, 함수 이름이 StudentPrint보다는 printStudentInfo가 좋겠습니다.

2017-05-27 05:32 UTC, utilForever commented on Solutions/LeeInkyu/Grade Management System/1/main.java
> +            std[i]=new Student(nameTmp,(byte)inputTmp[0],(byte)inputTmp[1],(byte)inputTmp[2]);
nextInt를 해서 byte로 변환하는건 비효율적입니다. nextInt보다는 nextByte를 사용하는게 좋겠습니다.

2017-05-27 05:36 UTC, utilForever requested changes
Handler를 도입해 입력/출력 부분과 처리 부분을 나눈다는 점은 괜찮은 접근법이었다고 생각합니다.
다만 멤버 변수나 함수의 이름 선택에 있어서 몇 가지 개선해야 될 점이 있어보입니다.
가독성을 위해 쉼표나 연산자 사이에 띄워쓰기가 있어도 괜찮겠군요.
몇 가지 수정해야 될 부분이 있어서 일단 승인은 보류합니다.
확인하신 뒤에 수정하셔서 커밋해주시면 확인 후에 머지하도록 하겠습니다.

2017-05-28 08:47 UTC, utilForever commented on Solutions/LeeInkyu/Grade Management System/01/Student.java
> +    public Student(String namePm, byte Kpm, byte Mpm, byte Epm)
저번에도 드렸던 질문이지만, Pm이 의미하는 뜻은 무엇인가요?

2017-05-28 08:49 UTC, utilForever approved these changes
피드백드렸던 부분을 많이 개선했네요. 고생하셨습니다.
몇 가지 팁을 드리자면, Java에서 멤버 변수는 소문자로 시작해서
단어마다 첫글자에 대문자를 씁니다 (예를 들어, printInfo).
그리고 멤버 변수는 단어 사이에 _를 씁니다 (예를 들어, korean_score).

2017-05-28 08:49 UTC, merged

2017-05-28 11:28 UTC, LeeInkyu commented on Solutions/LeeInkyu/Grade Management System/01/Student.java
> +    public Student(String namePm, byte Kpm, byte Mpm, byte Epm)
파라미터요... 빼는 게 좋을까요?

2017-05-28 11:28 UTC, LeeInkyu commented
감사합니다!

2017-05-28 11:29 UTC, utilForever commented on Solutions/LeeInkyu/Grade Management System/01/Student.java
> +    public Student(String namePm, byte Kpm, byte Mpm, byte Epm)
Pm이 파라미터였구나 앜ㅋㅋㅋㅋㅋ
근데 Pm만 봐서는 파라미터인지 잘 모르겠네요. T^T